core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('registration/', include('django.contrib.auth.urls')),
    # path('dashboard/', include('dashboard.urls')),

    # path('basket/', include('basket.urls', namespace='basket')),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path('checkout/', include('checkout.urls')),
    # path('orders/', include('orders.urls')),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard_with_pivot, name='dashboard_with_pivot'),
    path('data', views.pivot_data, name='pivot_data'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('products/', views.all_products, name='all_products'),
    path('single_product/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('product_create', views.product_create, name='product_create'),
    path('product_details/<int:pk>', views.product_detail, name='product_details'),
    path('product_update/<int:pk>', views.product_update, name='product_update'),
    path('product_delete/<int:pk>', views.product_delete, name='product_delete'),

    path('category/', views.all_categories, name='all_categories'),
    path('category_list_admin', views.category_list_admin, name="category_list_admin"),
    path('product_list_admin', views.product_list_admin, name="product_list_admin"),
    path('cart_list_admin', views.cart_list_admin, name="cart_list_admin"),
    path('cart_details_admin/<int:pk>', views.cart_details_admin, name="cart_details_admin"),

    path('add_to_cart/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('cart_summary/', views.cart_summary, name="cart_summary"),
    path('cart_success/', views.cart_success, name="cart_success"),

    path('search/<slug:category_slug>/', views.category_list, name='category_list'),
    path('category_details/<slug:category_slug>/', views.category_details, name='category_details'),
    path('category_create', views.category_create, name='category_create'),
    path('category_update/<int:pk>', views.category_update, name='category_update'),
    path('category_delete/<int:pk>', views.category_delete, name="category_delete"),

    path('design_inspiration/', views.design_inspiration, name='design_inspiration'),
    path('glass_morphism/', views.glass_morphism, name='glass_morphism'),

    path('furniture/', views.furniture, name='furniture'),
    path('accesories/', views.accesories, name='accesories'),

    path('registration/', views.registration, name='registration'),
    path('user_account/', views.user_account, name="user_account"),
    # path('registration/login/', auth_views.LoginView.as_view(template_name='registration/login.html')),
    # path('register', views.user_create_by_form, name='register'),

    # path('searchbox/', views.Searchbox, name='searchbox'),
]

dashboard/models.py
from django.db import models

from django.db import models


class Order(models.Model):
    product_category = models.CharField(max_length=20)
    payment_method = models.CharField(max_length=50)
    shipping_cost = models.CharField(max_length=50)
    unit_price = models.DecimalField(max_digits=5, decimal_places=2)

dashboard/views.py
from django.shortcuts import render

from django.http import JsonResponse
from django.shortcuts import render
from dashboard.models import Order
from django.core import serializers

def dashboard_with_pivot(request):
    return render(request, 'dashboard_with_pivot.html', {})


def pivot_data(request):
    dataset = Order.objects.all()
    data = serializers.serialize('json', dataset)
    return JsonResponse(data, safe=False)

templates/Searchbox.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Searchbox{% endblock %}


{% block content %}

<form class="search" action="{% url 'search' %}" method='post'>
  {% csrf_token %}
  <input type="search" placeholder="Search here..." name="usr_query"
      value='{{ query }}' required>
  <button type="submit">Search</button>
</form>


    <h1>Search Result</h1>
    <ul>
        {% for product in products %}
        <li>
          {{ product.name }}, {{ product.price }}
        </li>
        {% endfor %}
    </ul>



{% endblock %}

templates/accesories.html
{% extends "base.html" %}
{% load static %}

{% block title %}Accesories{% endblock %}


{% block content %}


<div class="container-fluid">
    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {% for subcategory in categories %}
            {% if subcategory.parent.id == category.id %}
                <li><a class="dropdown-item" id="submeniu"
                       href="#">{{ subcategory.name }}</a></li>
            {% endif %}

        {% endfor %}
      </ul>
</div>

    {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"/>
    <title>{% block title %}My shop{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6a23276998.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<style>






    {#.navbar-scroll .nav-link,#}
    {#.navbar-scroll .navbar-toggler-icon,#}
    {#.navbar-scroll .navbar-brand {#}
    {#    color: #fff;#}
    {#}#}
    {##}
    {#/* Color of the links AFTER scroll */#}
    {#.navbar-scrolled .nav-link,#}
    {#.navbar-scrolled .navbar-toggler-icon,#}
    {#.navbar-scrolled .navbar-brand {#}
    {#    color: #fff;#}
    {#}#}
    {##}
    {#/* Color of the navbar AFTER scroll */#}
    {#.navbar-scroll,#}
    {#.navbar-scrolled {#}
    {#    background-color: #cbbcb1;#}
    {#}#}
    {##}
    {#.mask-custom {#}
    {#    backdrop-filter: blur(5px);#}
    {#    background-color: rgba(255, 255, 255, .15);#}
    {#}#}
    {##}
    {#.navbar-brand {#}
    {#    font-size: 1.75rem;#}
    {#    letter-spacing: 3px;#}
    {#}#}
.navbar{
   background-color: rgba(255, 255, 255, 0.3);
    -webkit-backdrop-filter: blur(10px);
        backdrop-filter: blur(10px);
text-decoration:none;
border-radius: 20px;
    padding: 20px;
    box-shadow: 0 5px 10px rgba(127, 63, 191, 0.7);


}
.navbar-toggler{
             background: #fff;
            box-shadow: 0 5px 10px rgba(0, 0, 0, 1);
    border-left: 50px;
    border-right: 50px;
        }

#aaa{
    text-decoration: black;
}
.nowrap{
    white-space: nowrap;
}
.navbar .nav-link > li > a,
        .navbar .nav-link > .active > a {
            color: #878782 ;
        }

        .navbar-nav .nav-item > a:hover {
            color: #7f3fbf !important;

        }
.navbar-nav .nav-item > a {
            color:#878782 !important;

        }
        #submeniu > a:hover {
            color: #7f3fbf !important;
        }

        #pagina {
            margin-left: 20px;
            margin-right: 20px;
        }
#cautare{
  border-radius: 20px;
}
#login{
  border-radius: 20px;
    border-color: #9c46e8;
    color: #878782;
    }
#login:hover{
background-color:#d7a4eb;

    }
#logout{
  border-radius: 20px;
    border-color: #9c46e8;
    color: #878782;

    }
#logout:hover{
background-color:#d7a4eb;
    }
#inregistrare{
  border-radius: 20px;
    border-color: #9c46e8;
    color: #878782;
    }
#inregistrare:hover{
background-color:#d7a4eb;
    }
    #cos{
      border-radius: 20px;
        background-color:#d7a4eb;
    }

</style>
<body>
<div class="navbar" >
    <nav class="navbar navbar-expand-md  fixed-top  mx-25px">
        <div class="container-fluid">
            <a href={% url 'store:home' %}>
                <img src="http://127.0.0.1:8000/media/images/Rainbow%20Candy%20shop%20logo.png"
                     width="100px"
                     height="50px">
            </a>
            <button class="navbar-toggler" type="button" data-mdb-toggle="collapse"
                    data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="true" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="true" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse show navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    {% if request.user.is_superuser %}

                        <li class="nav-item"id="aaa">
                            <a href="{% url 'store:category_list_admin' %}" class="nav-link nowrap">
                                Category List</a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'store:product_list_admin' %}" class="nav-link nowrap">
                                Product List</a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'store:cart_list_admin' %}" class="nav-link nowrap">
                                Cart List</a>
                        </li>

                    {% else %}
                        {% for category in categories %}
                            {% if not category.parent %}

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle nowrap" href="#"
                                       id="navbarDropdownMenuLink" role="button"
                                       data-bs-toggle="dropdown" aria-expanded="false">
                                        {{ category.name }}

                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        {% for subcategory in categories %}
                                            {% if subcategory.parent.id == category.id %}
                                                <li><a class="dropdown-item" id="submeniu"
                                                       href="{% url 'store:category_details' category_slug=subcategory.slug %}">{{ subcategory.name }}</a>
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                </li>
                            {% endif %}

                        {% endfor %}
                        <li class="nav-item">
                            <a href="{% url 'store:design_inspiration' %}" class="nav-link nowrap">Design
                                Inspiration</a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'store:glass_morphism' %}" class="nav-link nowrap">Glass
                                Morphism</a>
                        </li>
                    {% endif %}
                </ul>
                <form class="d-flex">
                    <input id="cautare" class="form-control me-2 col-3 nowrap" type="search" placeholder="Search"
                           aria-label="Search">
                </form>

                {% if is_logged_in %}
                    <a id="login" href="{% url 'logout' %}" class="btn  mx-2 nowrap">Log out</a>
                {% else %}
                    <a id="inregistrare" href="{% url 'store:registration' %}" class="btn  mx-2 nowrap">Register</a>
                    <a  id="logout" href="{% url 'login' %}" class="btn mx-2 nowrap" type="submit">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-person-check-fill" viewBox="0 0 16 16">
                            <path fill-rule="evenodd"
                                  d="M15.854 5.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L12.5 7.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                            <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                        </svg>
                        Log In</a>
                {% endif %}

                <a id="cos" href="{% url 'store:cart_summary' %}" class="btn  mx-2 nowrap" type="button"
                   role="button">
                    <span class="badge badge-pill red"> </span>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-cart2" viewBox="0 0 16 16">
                        <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>
                    </svg>
                    Cart
                </a>
            </div>
        </div>

    </nav>


    <div style="margin-top:70px">
        {% block content %}

        {% endblock %}
    </div>
</div>
</body>
</html>

templates/dashboard.html
{% load static %}

{% block content %}
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        h1 {
            color: #fed943;
            font-weight: 600;
            font-size: 3rem;
            opacity: 0.8;
        }

        h2,
        p {
            color: #4b4b4b;
            font-weight: 500;
            opacity: 0.8;
        }

        h3 {
            color: #4b4b4b;
            font-weight: 600;
            opacity: 0.8;
        }

        main {
            font-family: "Poppins", sans-serif;
            min-height: 100vh;
            background: linear-gradient(to right top, #ffd400, #ffb733);
            display: flex;
            align-items: center;
            justify-content: center;
        }

        .glass {
            background: white;
            min-height: 80%;
            width: 65%;
            background: linear-gradient(
                    to right bottom,
                    rgba(255, 255, 255, 0.7),
                    rgba(255, 255, 255, 0.3)
            );
            border-radius: 2rem;
            z-index: 2;
            backdrop-filter: blur(2rem);
            display: flex;
        }

        .circle1,
        .circle2 {
            background: white;
            background: linear-gradient(
                    to right bottom,
                    rgba(255, 255, 255, 0.8),
                    rgba(255, 255, 255, 0.3)
            );
            height: 20rem;
            width: 20rem;
            position: absolute;
            border-radius: 50%;
        }

        .circle1 {
            top: 5%;
            right: 15%;
        }

        .circle2 {
            bottom: 5%;
            left: 10%;
        }

        .dashboard {
            flex: 1;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: space-evenly;
            text-align: center;
            background: linear-gradient(
                    to right bottom,
                    rgba(255, 255, 255, 0.7),
                    rgba(255, 255, 255, 0.3)
            );
            border-radius: 2rem;

        }

        .link {
            display: flex;
            margin: 2rem 0rem;
            padding: 1rem 5rem;
            align-items: center;
        }

        .link h2 {
            padding: 0rem 2rem;
        }

        .games {
            flex: 2;
        }

        {#.pro {#}
        {#    background: linear-gradient(to right top, #65dfc9, #6cdbeb);#}
        {#    border-radius: 2rem;#}
        {#    color: white;#}
        {#    padding: 1rem;#}
        {#    position: relative;#}
        {#}#}
        {##}
        {#.pro img {#}
        {#    position: absolute;#}
        {#    top: -10%;#}
        {#    right: 10%;#}
        {#}#}
        {##}
        {#.pro h2 {#}
        {#    width: 40%;#}
        {#    color: white;#}
        {#    font-weight: 600;#}
        {#}#}

        /* GAMES */
        .status {
            margin-bottom: 3rem;
        }

        .status input {
            background: linear-gradient(
                    to right bottom,
                    rgba(255, 255, 255, 0.7),
                    rgba(255, 255, 255, 0.3)
            );
            border: none;
            width: 50%;
            padding: 0.5rem;
            border-radius: 2rem;
        }

        .games {
            margin: 5rem;
            display: flex;
            flex-direction: column;
            justify-content: space-evenly;
        }

        .card {
            display: flex;
            background: linear-gradient(
                    to left top,
                    rgba(255, 255, 255, 0.8),
                    rgba(255, 255, 255, 0.5)
            );
            border-radius: 1rem;
            margin: 2rem 0rem;
            padding: 2rem;
            box-shadow: 6px 6px 20px rgba(122, 122, 122, 0.212);
            justify-content: space-between;
        }

        .progress {
            background: linear-gradient(to right top, #65dfc9, #6cdbeb);
            width: 100%;
            height: 25%;
            border-radius: 1rem;
            position: relative;
            overflow: hidden;
        }

        .progress::after {
            content: "";
            width: 100%;
            height: 100%;
            background: rgb(236, 236, 236);
            position: absolute;
            left: 60%;
        }

        .card-info {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
        }

        .percentage {
            font-weight: bold;
            background: linear-gradient(to right top, #65dfc9, #6cdbeb);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
        }

        {#* {#}
        {#    margin: 0;#}
        {#    padding: 0;#}
        {#    box-sizing: border-box;#}
        {##}
        {#}#}
        {##}
        {#body {#}
        {#    position: relative;#}
        {#    display: flex;#}
        {#    justify-content: center;#}
        {#    align-items: center;#}
        {#    min-height: 100vh;#}
        {#    background: #350048;#}
        {#}#}

        .container {
            width: 600px;
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;

        }

        .container .btn {
            position: relative;
            width: 155px;
            height: 50px;
            margin: 20px;

        }

        .container .btn a {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            display: flex;
            justify-content: center;
            align-items: center;
            background: rgba(255, 255, 255, 0.05);
            box-shadow: 0 15px 35px rgba(0, 0, 0, 0.02);
            border-top: 1px solid rgba(255, 255, 255, 0.1);
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            border-radius: 30px;
            color: #4b4b4b;
            z-index: 1;
            font-weight: 400;
            letter-spacing: 1px;
            text-decoration: none;
            overflow: hidden;
            transition: 0.5s;
            backdrop-filter: blur(15px);
        }

        .container .btn:hover a {
            letter-spacing: 3px;
        }

        .container .btn a:before {
            content: '';
            position: absolute;
            top: 0;
            left: 0;
            width: 50%;
            height: 100%;
            background: linear-gradient(to left, rgba(255, 255, 255, 0.15), transparent);
            transform: skewX(45deg) translateX(0);
            transition: 0.5s;
        }

        .container .btn:hover a:before {
            transform: skewX(45deg) translateX(100px);
        }

        .container .btn:before {
            content: '';
            position: absolute;
            left: 50%;
            transform: translateX(-50%);
            bottom: -5px;
            width: 30px;
            height: 10px;
            background: #f00;
            border-radius: 10px;
            transition: 0s;

        }

        .container .btn:hover::before {
            bottom: 0;
            height: 50%;
            width: 80%;
            border-radius: 30px;
            transition-delay: 0.5s;
        }

        .container .btn::after {
            content: '';
            position: absolute;
            left: 50%;
            transform: translateX(-50%);
            top: -5px;
            width: 30px;
            height: 10px;
            background: #f00;
            border-radius: 10px;
            transition: 0s;

        }

        .container .btn:hover::after {
            top: 0;
            height: 50%;
            width: 80%;
            border-radius: 30px;
            transition-delay: 0.5s;
        }

        .container .btn:nth-child(4)::before,
        .container .btn:nth-child(4)::after {
            background: #ff1f71;
            box-shadow: 0 0 5px #ff1f71,
            0 0 15px #ff1f71,
            0 0 30px #ff1f71,
            0 0 60px #ff1f71;
        }

        .container .btn:nth-child(2)::before,
        .container .btn:nth-child(2)::after {
            background: #49D3CC;
            box-shadow: 0 0 5px #49D3CC,
            0 0 15px #49D3CC,
            0 0 30px #49D3CC,
            0 0 60px #49D3CC;
        }

        .container .btn:nth-child(3)::before,
        .container .btn:nth-child(3)::after {
            background: #49D3CC;
            box-shadow: 0 0 5px #49D3CC,
            0 0 15px #49D3CC,
            0 0 30px #49D3CC,
            0 0 60px #49D3CC;
        }

        .container .btn:nth-child(1)::before,
        .container .btn:nth-child(1)::after {
            background: #49D3CC;
            box-shadow: 0 0 5px #49D3CC,
            0 0 15px #49D3CC,
            0 0 30px #49D3CC,
            0 0 60px #49D3CC;
        }
        .container .btn:nth-child(5)::before,
        .container .btn:nth-child(5)::after {
            background: #6A1B9A;
            box-shadow: 0 0 5px #6A1B9A,
            0 0 15px #6A1B9A,
            0 0 30px #6A1B9A,
            0 0 60px #6A1B9A;
        }
    </style>




    <body>
    <main>
        <section class="glass">
            <div class="dashboard">
                <div class="user">
                    <img src="./images/avatar.png" alt=""/>
                    <h2>Dashboard</h2>
                    {#            <p>Pro Member</p>#}
                </div>
                <div class="links">
                    <div class="link">
                        <img src="./images/twitch.png" alt=""/>
                        <h3>Categories</h3>
                    </div>
                    <div class="link">
                        <img src="./images/steam.png" alt=""/>
                        <h3>Products</h3>
                    </div>
                    <div class="link">
                        <img src="./images/upcoming.png" alt=""/>
                        <h3>Carts</h3>
                    </div>
                    <div class="link">
                        <img src="./images/library.png" alt=""/>
                        <h3>Reports</h3>
                    </div>
                </div>
{#                <div class="pro">#}
{#                    <h2>Join pro for free games.</h2>#}
{#                    <img src="./images/controller.png" alt=""/>#}
{#                </div>#}
            </div>
            <div class="games">
                <div class="status">
{#                    <h1>Active Games</h1>#}
                    <div class="container">
                        <div class="btn"><a href="#"> Add<?</a></a></div>
                        <div class="btn"><a href="#"> Update<?</a></a></div>
                        <div class="btn"><a href="#"> Delete<?</a></a></div>
                    </div>
                    <div class="cards">
                        <div class="card">
                            <img src="#" alt=""/>
                            <div class="card-info">
                                <h2>Natural bed</h2>
                                <p>PS5 Version</p>
                                {#                            <div class="progress"></div>#}
                            </div>
                            {#                        <h2 class="percentage">60%</h2>#}
                        </div>
                    </div>
                    <div class="card">
                        <img src="./images/sackboy.png" alt=""/>
                        <div class="card-info">
                            <h2>Sackboy A Great Advanture</h2>
                            <p>PS5 Version</p>
                            <div class="progress"></div>
                        </div>
                        <h2 class="percentage">60%</h2>
                    </div>
                    <div class="card">
                        <img src="./images/spiderman.png" alt=""/>
                        <div class="card-info">
                            <h2>Spiderman Miles Morales</h2>
                            <p>PS5 Version</p>
                            <div class="progress"></div>
                        </div>
                        <h2 class="percentage">60%</h2>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <div class="circle1"></div>
    <div class="circle2"></div>
    </body>

{% endblock %}

templates/dashboard_with_pivot.html
<head>
  <meta charset="UTF-8">
  <title>Dashboard with Flexmonster</title>
  <script src="https://cdn.flexmonster.com/flexmonster.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <link rel="stylesheet" href="https://cdn.flexmonster.com/demo.css">
</head>
<body>
<div id="pivot-table-container" data-url="{% url 'pivot_data' %}"></div>
<div id="pivot-chart-container"></div>



function processData(dataset) {
    var result = []
    dataset = JSON.parse(dataset);
    dataset.forEach(item => result.push(item.fields));
    return result;
}
$.ajax({
    url: $("#pivot-table-container").attr("data-url"),
    dataType: 'json',
    success: function(data) {
        new Flexmonster({
            container: "#pivot-table-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {}
            }
        });
        new Flexmonster({
            container: "#pivot-chart-container",
            componentFolder: "https://cdn.flexmonster.com/",
            width: "100%",
            height: 430,
            //toolbar: true,
            report: {
                dataSource: {
                    type: "json",
                    data: processData(data)
                },
                slice: {},
                "options": {
                    "viewType": "charts",
                    "chart": {
                        "type": "pie"
                    }
                }
            }
        });
    }
});


{#Add it to the dataSource property of the report:#}
{##}
{#mapping: {#}
{#    "product_category": {#}
{#        "caption": "Product Category",#}
{#        "type": "string"#}
{#    },#}
{#    "payment_method": {#}
{#        "caption": "Payment Method",#}
{#        "type": "string"#}
{#    },#}
{#    "shipping_cost": {#}
{#        "caption": "Shipping Cost",#}
{#        "type": "number"#}
{#    },#}
{#    "unit_price": {#}
{#        "caption": "Unit Price",#}
{#        "type": "number"#}
{#    }#}
{#}#}
</body>

templates/furniture.html
{% extends "base.html" %}
{% load static %}

{% block title %}Furniture{% endblock %}


{% block content %}
    <div class="container mx-25">
        <div class="row row-cols-3 row-cols-sm-2 row-cols-md-3 g-3 mx-2 my-2">
            {% for category in categories %}
                {% if not category.parent %}

                    {#                    <div class="col">#}
                    {#                <div class="card shadow-sm">#}
                    {#                    <img src="{{ product.image.url }}">#}
                    {#                    <div class="card-body">#}
                    {#                        <p class="card-text"> {{ product.title }}.</p>#}
                    {#                        <p class="card-text"> Price: {{ product.price }} € </p>#}
                    {#                        <div class="d-flex justify-content-between align-items-center">#}
                    {#                            <div class="btn-group">#}
                    {#                                <a href="{% url 'store:product_detail' product_slug=product.slug %}" type="button"#}
                    {#                                   class="btn btn-sm btn-outline-warning">View details</a>#}
                    {#                            </div>#}
                    {##}
                    {#                            <button type="button" class="btn btn-sm btn-warning">#}
                    {#                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"#}
                    {#                                     class="bi bi-cart2" viewBox="0 0 16 16">#}
                    {#                                    <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l1.25 5h8.22l1.25-5H3.14zM5 13a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"></path>#}
                    {#                                </svg>#}
                    {#                                Add to cart#}
                    {#                            </button>#}
                    {#                        </div>#}
                    {#                    </div>#}
                    {#                </div>#}
                    {#            </div>#}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {{ category.name }}
                        </a></li>
                {% endif %}

            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}